spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3308/jcms2018?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Chongqing&useSSL=true
    username: py
    password: 123
  thymeleaf:
    cache: false
  redis:
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

debugModel: true